### ISSUE TITLE
Fonts ugly on 21.10

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/libreoffice#11]
Fonts look awful on 21.10 (wayland only), but fine on 21.04 and 20.04. This has started to be a problem on Impish with Libreoffice snap versions 7.2.0 and newer.

![Screenshot from 2021-09-17 10-45-49](https://user-images.githubusercontent.com/12970280/133824612-2ec373f5-f60a-42c1-842f-8a5816a3ba82.png)

The fonts look normal on an xorg session so this is specific to wayland.

See also: https://forum.snapcraft.io/t/snap-application-have-very-bad-font-rendering-in-ubuntu-21-10/26415/5

**Comment by vanvugt** [comment]
I'm guessing this is the same issue as https://bugs.launchpad.net/bugs/1936747
