### ISSUE TITLE
Add Occitan to the list of built languages

### ISSUE THREAD

**Issue by ensag-dev** [ubuntu/libreoffice#20]
Hello,
would it be possible to add the Occitan language to the list?
And also in the spellchecking section?

Best regards!

**Comment by fitojb** [comment]
I think you need to add `hunspell-oc` (new in Jammy, so only for the 7.3 series) as well as the code `oc` to snapcraft.yaml

I don’t know how to test these changes in a Launchpad builder, though.

**Comment by fitojb** [comment]
@RicoTz has fixed this with commits https://github.com/ubuntu/libreoffice/commit/408c908dfe24059c69355a0c35571b16d9bc8a7b and https://github.com/ubuntu/libreoffice/commit/8a8c5c7fa9182898fc9827686c90b5ee75a2c56b. Thanks!
