### ISSUE TITLE
LO Snap in Snap Store doesn't actually use LZO compression

### ISSUE THREAD

**Issue by Constancies** [ubuntu/libreoffice#33]
Despite this project's `snapcraft.yaml` specifying the use of LZO compression, the built Snap (found at https://snapcraft.io/libreoffice) does not actually use LZO compression. Why is this, and how can it be fixed?

**Comment by seb128** [comment]
Thanks for the bug report. In fact lzo is the default now and snapd doesn't expose the format but it is using lzo

$ sudo file /var/lib/snapd/snaps/libreoffice_302.snap 
/var/lib/snapd/snaps/libreoffice_302.snap: Squashfs filesystem, little endian, version 4.0, lzo compressed, 1135050607 bytes, 31950 inodes, blocksize: 131072 bytes, created: Wed Nov 22 08:11:59 2023
