### ISSUE TITLE
Libreoffice 7.2.0 missing Breeze dark icons

### ISSUE THREAD

**Issue by aConar** [ubuntu/libreoffice#4]
Hi, recently Libreoffice snap version was updated to 7.2.0 (from 7.1.5). Two important bug that I realize till now are: Missing breeze dark icons, or any other dark icon theme. Other serius issue is when opened several Impress presentations that I use often in classes (I used it with 7.1.5 without any problem) almost all images are gone. Also embebed videos playback in wrong places.

lsb_release -a
No LSB modules are available.
Distributor ID: Neon
Description:    KDE neon User Edition 5.22
Release:        20.04
Codename:   focal

libreoffice snap:
name:      libreoffice
summary:   LibreOffice is a free and open source office suite
publisher: Canonical✓
store-url: https://snapcraft.io/libreoffice
contact:   https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bugs?field.tag=snap
license:   MPL-2.0
description: |
  LibreOffice is a free and open source office suite, developed by The Document Foundation. The
  LibreOffice suite comprises programs for word processing, the creation and editing of
  spreadsheets, slideshows, diagrams and drawings, working with databases, and composing
  mathematical formulae.
snap-id: CpUkI0qPIIBVRsjy49adNq4D6Ra72y4v
channels:
  latest/stable:    7.2.0.4 2021-09-03 (227) 732MB -
  latest/candidate: 7.2.0.4 2021-09-03 (227) 732MB -
  latest/beta:      ↑                              
  latest/edge:      7.2.0.4 2021-08-27 (227) 732MB -

**Comment by hellsworth** [comment]
This has been fixed in the libreoffice build 229, now available in the --stable snap store.
