### ISSUE TITLE
Snap Libreoffice 7.2.0.4 breaks graphics

### ISSUE THREAD

**Issue by Craig-Horrocks** [ubuntu/libreoffice#5]
I have had to uninstall this as it broke the graphics.
Reported by other users in Ubuntu Software.
Fixed for myself by uninstalling and installing from .deb

**Comment by etlam** [comment]
We can confirm that all images inside of documents are missing.  
@Craig-Horrocks Did you install version 7.2.0.4 (the same version) from .deb? So it is just an error of the snap version?

**Comment by Craig-Horrocks** [comment]
Hi Malte
      
      Confirmed.  Installed same version from deb.
      
      All docs worked and rendered images correctly.
      
      Export from DRAW to jpg and png also works correctly.
      
      Conclusion that just an error in snap seems reasonable.
      
      Hope this helps
      Craig
    
    
      
    On 8/09/21 9:17 pm, Malte Müns wrote:
    
    
      
      We can confirm that all images inside of documents are missing.
        @Craig-Horrocks Did you install
        version 7.2.0.4 (the same version) from .deb? So it is just an
        error of the snap version?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ubuntu/libreoffice/issues/5#issuecomment-915064852",
"url": "https://github.com/ubuntu/libreoffice/issues/5#issuecomment-915064852",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hellsworth** [comment]
Yep thanks so much for letting us know about the broken jpeg images in writer! We've added `--with-system-jpeg` to likely solve this issue and it is [building on launchpad](https://launchpad.net/~hellsworth/+snap/libreoffice-jpeg-fix). Once I verify it has been fixed, we'll release a new libreoffice :)

**Comment by Craig-Horrocks** [comment]
Hi Team
      
      It was not just jpegs - svg, png - all graphics insert or export
      were affected.
      
      Cheers
      Craig
    
    
      
    On 9/09/21 8:26 am, Heather Ellsworth
      wrote:
    
    
      
      Yep thanks so much for letting us know about the broken jpeg
        images in writer! We've added --with-system-jpeg
        to likely solve this issue and it is building on launchpad.
        Once I verify it has been fixed, we'll release a new libreoffice
        :)
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ubuntu/libreoffice/issues/5#issuecomment-915545998",
"url": "https://github.com/ubuntu/libreoffice/issues/5#issuecomment-915545998",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kenvandine** [comment]
png and PDF worked for me, I didn't try svg.  The only format I was able to reproduce a problem with was jpeg.

**Comment by etlam** [comment]
@hellsworth Thank you for your work!  
Would it be possible to also update the `latest/stable` channel of the snap?
Thanks in advance!

**Comment by kenvandine** [comment]
I've confirmed jpg, png, gif, pdf, and SVG all works with rev 229 in edge.  @hellsworth let's work on getting this promoted to stable next week.

**Comment by hellsworth** [comment]
It is available in stable now, in build 229 :)

**Comment by etlam** [comment]
@hellsworth Thank you for your awesome work!
